spring:
  datasource:
    url: jdbc:mysql://localhost:3306/langchain_diet?useSSL=false&serverTimezone=UTC
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  ai:
    openai:
      api-key: ${OPENAI_KEY}
  http:
    client:
      factory: jdk

langchain4j:
  chat:
    model:
      provider: openai
      api-key: ${OPENAI_KEY}
      model-name: gpt-3.5-turbo
      temperature: 0.7
      max-tokens: 1000


app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: 86400000

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
